version: '2.0'
services:
  web:
    build: .
    volumes:
      - .:/floap
    ports:
      - "3000:3000"
    depends_on:
      - "db"
    command: "bundle exec rails s -p 3000 -b '0.0.0.0'"
  db:
    image: mysql:5.7.17
    ports:
      - "3306:3306"
